### ISSUE TITLE
Ability to add video posts?

### ISSUE THREAD

**Issue by oooShiny** [williamsdb/php2Bluesky#10]
I'm looking to upload short video clips to Bluesky programmatically, and I came across some gists by [mozzius](https://gist.github.com/mozzius) that seem to show that it's possible. Is that something that can be added here?

**Comment by williamsdb** [comment]
Looking at that I think it is done via the back door, so to speak, through knowledge gained through his work at Bluesky. There isn't any support in the official API as yet. [This article](https://docs.bsky.app/blog/tags/community#whats-in-the-future-for-skyfeed) from May regarding "What's in the future for SkyFeed?" says:

> Support for videos, audio and other media content with a new custom lexicon in a backwards-compatible way. They will use the storage network I'm working on, but with an atproto-compatible blob format. The main difference is that it uses the BLAKE3 hash function instead of SHA256 and has no file size limit

I'd rather wait and support via the official route than go through something that might change. Once it is available I will add support.
