### ISSUE TITLE
Image Upload Issue - Suggestion

### ISSUE THREAD

**Issue by compujeramey** [williamsdb/php2Bluesky#11]
Hello,

Ran into an issue that I wanted to document should it save someone else some time.

In building link cards, the repo works wonderfully. Except seemingly random posts/images would fail. I ultimately found that Bluesky seems to accept images over 1mb, but they don't seem to work when creating the link card. The API would generate a 400 status response to my post even though my media library succeeded with a 200 response.

Not sure if it is appropriate to include a comment in this repo to clue others in to that potential issue. The actual documentation on the API seems currently less than ideal.

**Comment by BearlyDoug** [comment]
YIPES! Forgot about one more change needed within the "post_to_bluesky" function.

CHANGE
```
	// add any link cards
	if (!empty($link)){
		$embed = fetch_link_card($connection, $link);
	}
```

TO
```
	// add any link cards
	if (!empty($link)){
		$embed = fetch_link_card($connection, $link, $media);
	}
```

**Comment by williamsdb** [comment]
@compujeramey - I haven't been able to reproduce your issue. Are you able to provide me with a link that failed for you so I can test?

@BearlyDoug - I have committed your changes, thanks!

**Comment by BearlyDoug** [comment]
Appreciate it, @williamsdb. I'm also thinking that we might need to find a way to provide a fallback image, if the page (or site) doesn't have one available. I ran into this issue while using the link card and a URL for a WordPress page that didn't have a featured image assigned, and the default primary image was missing/removed. Maybe a centrally linked generic image somewhere? Something like https://picsum.photos/1024/536 would be perfect (randomly generated image every time).

**Comment by williamsdb** [comment]
I came across exactly that issue when I was testing and what I have done for now is simply fail saying that there is no image avalable. What I think I will do is provide the option of either picsum, a blank image, an image of your own choosing or to fail which should cover all the bases!

**Comment by compujeramey** [comment]
Yes, link cards.

I am able to upload either image to Bluesky, with the appropriate status back. But when I try to append that image to the rest of the link, I got a 400 bad request back for the larger image.

**Comment by compujeramey** [comment]
If I were to just manually take the link and paste it in Bluesky's web interface or app, it works. But I can't build and post it using the API without going to a smaller image, which leads me believe it was the 1 megabyte file size issue I was seeing discussed elsewhere.

For background, we built an automated article posting tool and it would fail, seemingly randomly, until I tried to isolating for the image size.

**Comment by williamsdb** [comment]
This is what I did to get the [post I sent earlier](https://bsky.app/profile/php2bluesky.bsky.social/post/3lcl6dw7qrb2c):

```
<?php

    require __DIR__ . '/../vendor/autoload.php';
    require __DIR__ . '/functions.php';

    $handle = 'php2bluesky.bsky.social';
    $password = 'abcd-efgh-ijkl-mnop';
    
    $text = "Testing link card changes.";

    $link = 'https://urbanmilwaukee.com/2024/11/30/op-ed-time-for-legislators-to-work-together/';

    // if you specifiy both media and link the latter takes precedence
    $response = post_to_bluesky($connection, $text, '', $link, $alt);
    print_r($response);

    $url = permalink_from_response($response, $handle);
    echo $url.PHP_EOL;
?>
```

Are you able to try some thing basic like that to see if you get the same error and/or provide a snippet of your code here for me to see?

**Comment by compujeramey** [comment]
Perhaps I am overcomplicating it if I don't have the upload the image first. 

I did something like this: 
```
$image = um_upload_media_to_bluesky($connection, $filename);

    $embed = [
      'embed' => [
        '$type' => 'app.bsky.embed.external',
        'external' => [
            'uri' => get_permalink($ID),
            'title' =>  html_entity_decode(get_the_title($ID)),
            'description' =>  html_entity_decode(get_the_excerpt($ID)),
            'thumb' => $image,
        ],
      ],
    ];
    $args['record'] = array_merge($args['record'], $embed);
    $connection->request('POST', 'com.atproto.repo.createRecord', $args);
```

**Comment by williamsdb** [comment]
Closing this now but if you still get issues let me know.

**Comment by compujeramey** [comment]
Thanks Neil - I was following your blog post here - https://www.spokenlikeageek.com/2023/11/09/posting-to-bluesky-via-the-api-from-php-part-four-link-cards/

**Comment by BearlyDoug** [comment]
@compujeramey, I was doing the same thing until I went to the final output (and downloaded the complete script).

That's when I realized we could change the image for link cards (hence my contributions above which are now incorporated).

Definitely download the full package from here and use the format shown in index.php.

@williamsdb, that file needs to be updated to reflect that you can now use a direct image URL, rather than leaving it blank. :)

**Comment by williamsdb** [comment]
Yes, I can see the issue now that it has been pointed out to me. The blog posts are more about _how I wrote_ the library and not _how to use_ the library.

With this in mind I have now amended all of the blog posts to have the following disclaimer in a yellow box:

`NOTE: This post is mainly about how I developed the php2Bluesky library. If you are looking for information on using the library in your own code please see here: https://github.com/williamsdb/php2Bluesky/`

I have also updated the README to include more examples on how to use the code and I will remove the links to the blog shortly. I am going to take a look at Github's wiki functionality over the weekend to see if that might be a suitable place for more detailed documentation.

Hopefully, this will address the issue that you both have encountered.
