### ISSUE TITLE
Need help configuring everything. First test is failing with invalid identifier or password

### ISSUE THREAD

**Issue by cyberfunk** [williamsdb/php2Bluesky#14]
I installed Composer with Home Brew. I downloaded repository an dinstalled everything (inlcuding Composer files) to a folder called BlueSky. I have updated the index with my credentials and created a separate test.php just using the send text example. Did I do somethign wrong? it fails with:

PHP Fatal error:  Uncaught RuntimeException: Invalid identifier or password

my credentials are entered as follows (I changed them to protect privacy)

$handle = '<johndoe.com>';
$password = '<****-****-****-****>';

**Comment by williamsdb** [comment]
Should look like this (no brackets):

```
    $handle = 'php2bluesky.bsky.social';
    $password = 'abcd-efgh-ijkl-mnop';
```

Obviously if you have changed your Bluesky handle to johndoe.com then the handle should be that.

If that doesn't work let me know and we can take it from there.

**Comment by cyberfunk** [comment]
Aha! Thanks so much!!! They never tell you how much of the code to replace.🤣 I think the best way is to just use an exact example as you did above because many people are new to coding and may get confused. Although I am not new I still did not realize I should remove those brackets.🤦🏼‍♂️

**Comment by williamsdb** [comment]
Glad that you got it working. I guess that the brackets are in the blog post. I will probably put an example in the readme file as that'll be easier to maintain. Thanks for pointing that out.

**Comment by cyberfunk** [comment]
No worried and thanks for all of your hard work! The index.php file has brackets <> for all of the items to be replaced as well.

**Comment by williamsdb** [comment]
Ah yes. For now I have added a comment into index.php to try anc cover this but will also add to the documentation
`
// change the follow to your details without the <>`
