### ISSUE TITLE
hashtags with are truncated

### ISSUE THREAD

**Issue by eiland-asbl** [williamsdb/php2Bluesky#15]
Hashtags with #a-dash or #an_underscore are truncated to #a and #an, although they should work.

It seems even that [#adsfl-_#@#!@](https://bsky.app/hashtag/adsfl_dfljdf%23dff-df%2Fdf%3Fgrsfdg) should also work. Just not spaces.

**Comment by williamsdb** [comment]
Hi, I have rewritten the hashtag code to use the same regex as is used by Atproto so these should now work. I am currently testing and will push my changes shortly.
