### ISSUE TITLE
Usernames are not converted into links

### ISSUE THREAD

**Issue by PDelahanty** [williamsdb/php2Bluesky#2]
If you make a post and include a username (such as @someone.bsky.social or @domainname.com ), they are not converted into links to the user's profile.

**Comment by williamsdb** [comment]
Thanks for the heads-up. I'll have a look in the documentation to see how the conversion is done and update the code accordingly. Give me a few days to investigate and update.

**Comment by williamsdb** [comment]
Ok, this is now done and in the latest code. You don't need to do anything differently as the code will look for and handle mentions automatically. If the handle given doesn't exist it will be silently dropped, i.e won't be converted to a link

**Comment by williamsdb** [comment]
Marking as closed.
