### ISSUE TITLE
Can I specify one URL and use PHP to retrieve only one bluesky post by someone else?

### ISSUE THREAD

**Issue by e1blue** [williamsdb/php2Bluesky#4]
I want to retrieve someone else's specific post. if I am using Bluesky and happen to find a post I like, can I use PHP to retrieve that one post? I want to embed it in my blog and display it.

**Comment by williamsdb** [comment]
Yes but you don't need my library to do that. I have written a blog post that explains what you need to do and you can [read that here](https://www.spokenlikeageek.com/2024/01/26/posting-to-bluesky-via-the-api-from-php-part-eight-retrieving-a-post/).

I have also updated the library to include a function (get_from_bluesky) should you wish to use that to get the post.

**Comment by e1blue** [comment]
Thank you for writing the blog post and updating the library.
Thanks to you, my questions have been answered.
It was very helpful.
