### ISSUE TITLE
bluesky_connect needs to be refactored a little bit

### ISSUE THREAD

**Issue by pixeline** [williamsdb/php2Bluesky#5]
https://github.com/williamsdb/php2Bluesky/blob/1e3f60822c87b0f1f35751cb52cf5f5f1efc5ef3/src/functions.php#L9

Thanks a lot for this!

A minor update: the bluesky_connect() function should be refactored:

```php 
function bluesky_connect($handle, $password)
{
    $connection = new BlueskyApi();
    $connection->auth($handle, $password);
    return $connection;
}
``` 

Other than that, your functions work great, thank you for sharing!

**Comment by williamsdb** [comment]
Thanks for the kind words.

Sorry for the delay but I have made the change. It will only work if you have cjrasmussen\BlueskyApi\BlueskyApi version 2.0 or above.

Thanks for pointing it out.
