### ISSUE TITLE
Can I post audio to Bluesky?

### ISSUE THREAD

**Issue by zecul** [williamsdb/php2Bluesky#7]
I followed your post https://www.spokenlikeageek.com/2023/11/09/posting-to-bluesky-via-the-api-from-php-part-four-link-cards/ and found a way to post my urls as hyperlink. thank you.

Is there anyway to post it as an audioplayer?

The page in question has an html player linked to AWS audio files:
https://bsky.app/profile/furtherrecords.bsky.social/post/3l3fmodvdbo2e

Is this possible or still unsupported by bluesky?

**Comment by williamsdb** [comment]
Hi

I have had a look at the [post you linked](https://bsky.app/profile/furtherrecords.bsky.social/post/3l3fmodvdbo2e) but that just seems to have a URL attachment and not any audio file. Can you check that the link you posted is correct and also let me know what device you were using at the time?

Thanks

Neil

**Comment by zecul** [comment]
Hi Neil, I posted the URL attachment only because  I couldn't make audio URL work. I used pipedream API to make the post.

I would love to post the same URL with an audio player that can programmatically pull the correct audio files from either the html player on the URL page or from the shopify metafield backend that provides the audio to that player via AWS links.

(pardon my terminology, not a programmer!)

Thanks
Mark

**Comment by zecul** [comment]
I'm doing all this via GPT (because I can't program) and it told me:

"Unfortunately, posting a direct AWS audio file URL (like an .mp3 hosted on Amazon S3) will not generate a playable audio card on Bluesky. Currently, Bluesky's link card functionality is limited to creating previews for certain types of external content (like webpages, YouTube, Spotify, and SoundCloud) but does not directly support playable audio embeds from arbitrary URLs, including AWS-hosted files.

If you post an AWS URL, Bluesky will likely just treat it as a standard link and create a link card preview based on the metadata from the URL (if available), but it won’t show a playable audio player in the post. You would need to use a service like SoundCloud or Spotify, which is natively supported in Bluesky for audio playback.

What Happens When Posting an AWS Audio Link:
AWS URL: Bluesky will try to generate a preview based on the URL, but since audio files (e.g., .mp3) don’t include metadata like title, description, or images, the preview will likely be minimal or nonexistent.
No Audio Player: Bluesky currently doesn't have native support for directly embedding an audio player from AWS or other direct links."

However, it didn't know how to make link cards either until I fed it your blog post.

**Comment by williamsdb** [comment]
Right, I understand. 

Bluesky doesn't support posting audio files. If, however, you post a link to a file on YouTube, SoundCloud, Spotify or Twitch then Bluesky will show either an audio or video player embedded in the post. 

So, it won't be possible to upload the mp3 file from S3 and if you upload a link to the file on S3 it will be shown as any other link.

I'm sure that will change in future but right now it's not possible.
