### ISSUE TITLE
Tags are not converted

### ISSUE THREAD

**Issue by hayglow** [williamsdb/php2Bluesky#9]
When I have tags in my variable $text, like "Here is a #tag. Have fun with it." #tag isn't converted in a clickable tag.

Would it be possible for you to implement this sometime?

You already implemented this for URLs and usernames, for the latter see https://github.com/williamsdb/php2Bluesky/issues/2 Thanks for this.

**Comment by williamsdb** [comment]
Hi, yes that seems now be possible via the api so I will take a look and update the library. Keep an eye here and I will announce on my blog https://spokenlikeageek.com when it is pushed. N

**Comment by williamsdb** [comment]
They are now! https://bsky.app/profile/spokenlikeageek.com/post/3lb6aww6ha22g

Let me know how you get on at https://bsky.app/profile/spokenlikeageek.com.
